[package]
name = "chip8_decompiler"
version = "0.1.0"
authors = ["bender <awsomearvinder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chip8_parser = {path = "../chip8_parser"}
